### ISSUE TITLE
Cant figure out how to install?

### ISSUE THREAD

**Issue by LoggerTheChicken** [baldursgate3/garrysbombs5#1]
How do i install this? when ever i extract the zip and put the folder in my addons folder my gmod crashes when i join singleplayer sandbox game

**Comment by baldursgate3** [comment]
@LoggerTheChicken, uninstall few addons and all if you have a lot. Please report back then.

**Comment by LoggerTheChicken** [comment]
@baldursgate3 well I used gbombs 5 before havnt got any new addons since and I have tried installing some other addons that are not from the workshop and Im having the same issue

**Comment by baldursgate3** [comment]
@LoggerTheChicken, gmod crashes because you've got a lot of content.

**Comment by LoggerTheChicken** [comment]
@baldursgate3 i fixed the issue, one of my addons became outdated the exact time I installed gbombs, thanks for the wonderful addon :)
